# Generated by Django 5.0.7 on 2025-11-22 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_direccion_zone_columnas_zone_filas_asiento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "codigo_ticket",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("esta_usado", models.BooleanField(default=False)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("fecha_uso", models.DateTimeField(blank=True, null=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
