# Generated by Django 5.2.8 on 2025-11-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price_min', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('SOLD', 'Ocupado')], default='AVAILABLE', max_length=15)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.zone')),
            ],
            options={
                'ordering': ['row_label', 'number'],
            },
        ),
    ]
