# Generated by Django 5.2.8 on 2025-12-01 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="reservation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="reserved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserved_seats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("RESERVED", "Reservado Temporalmente"),
                    ("SOLD", "Ocupado"),
                ],
                default="AVAILABLE",
                max_length=15,
            ),
        ),
    ]
