from abc import ABC, abstractmethod

class ReservationService(ABC):
    @abstractmethod
    def hold(self, user_id: str, event_id: int, zone_id: str, qty: int, ttl_minutes: int) -> str: ...
    @abstractmethod
    def release(self, reservation_id: str) -> None: ...
    @abstractmethod
    def confirm(self, reservation_id: str) -> None: ...
    @abstractmethod
    def is_expired(self, reservation_id: str) -> bool: ...
