# Generated by Django 5.2.8 on 2025-11-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Formato: AAAA-MM-DD', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
