# Generated by Django 5.0.7 on 2025-11-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="metodo_pago",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
