# Generated by Django 5.0.7 on 2025-11-21 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="direccion",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="columnas",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="zone",
            name="filas",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Asiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fila", models.CharField(max_length=10)),
                ("columna", models.PositiveIntegerField()),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asientos",
                        to="events.zone",
                    ),
                ),
            ],
            options={
                "unique_together": {("zona", "fila", "columna")},
            },
        ),
    ]
