# Generated by Django 5.2.8 on 2025-11-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_dni_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Formato: AAAA-MM-DD', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
